### ISSUE TITLE
Bad doc links on main page

### ISSUE THREAD

**Issue by bmc** [antlr/website-st4#2]
Not sure what the policy is for forking this repo, so I'm adding this as an issue.

**Page**: main index (index.html)

**Problem**: Several of the doc links (e.g., https://raw.githubusercontent.com/antlr/stringtemplate4/master/doc/index.md) point to Markdown documents using the "raw" GitHub URLs. Those URLs pull up raw, unrendered Markdown. The links should point to the regular repo link for the doc, to force GitHub to render the MD.

**Comment by parrt** [comment]
just resolved. thanks!
